added template for output
release-engineering/backvendor pull request #83
Opened 2018-10-02 09:19 UTC by jasinner

Fixes Issue #33

2018-10-02 10:24 UTC, twaugh reviewed
Thanks! Added some comments.

One idea for improving this would be to instead provide a function that parses the template, using the default value if the supplied template is empty. This would avoid having to parse the template multiple times, and the calls to Display() would be replaced by calls to t.Execute(), with a single call to the parsing function up front to get the template to use.

2018-10-02 10:24 UTC, twaugh commented on backvendor/display.go
> +		tmpl, err := template.New("output").Parse(defaultTemplate)
In this case perhaps we could just `customTemplate = defaultTemplate` (the caller is not affected by this) and fall through to the case where a custom template has been supplied.

2018-10-02 10:24 UTC, twaugh commented on backvendor/display.go
> +			return err
Once `tmpl.Execute(writer, ref)` is the last thing to do, If we aren't going to use anything like `errors.Wrap()` on the error we could just immediately return that result and leave the checking to the caller, e.g. `return tmpl.Execute(writer, ref)`.

2018-10-02 10:24 UTC, twaugh commented on backvendor/display_test.go
> +	}
We could verify `builder.String()` gives the result we expect in the no-error cases.

2018-10-02 10:24 UTC, twaugh commented on main.go
> +var template = flag.String("template", "", "go template to use for output with Rev, Tag and Ver")
I wonder if it's worth putting the default value here instead of having to work out whether to use a fallback in Display()? (But don't want to clutter the help output, so not sure...)

2018-10-02 10:24 UTC, twaugh commented on main.go
> +	backvendor.Display(&builder, template, ref)
Probably want to check the error.

2018-10-02 10:24 UTC, twaugh commented on backvendor/display.go
> +}
TemplateError isn't used.

2018-10-02 10:24 UTC, twaugh commented on backvendor/display.go
> +const defaultTemplate string = "@{{if .Rev}}{{.Rev}}{{end}}{{if .Tag}} ={{.Tag}}{{end}}{{if .Ver}} ~{{.Ver}}{{end}}"
I wonder whether to include the "top-level" indicator (currently "*") and the import path for the root of the repository in this template? That would allow for more complete customization.

2018-10-03 00:48 UTC, jasinner commented on backvendor/display.go
> +const defaultTemplate string = "@{{if .Rev}}{{.Rev}}{{end}}{{if .Tag}} ={{.Tag}}{{end}}{{if .Ver}} ~{{.Ver}}{{end}}"
That's not a requirement for me at the moment. Can we include that in a subsequent PR? I raised an issue for it:
https://github.com/release-engineering/backvendor/issues/84

2018-10-03 10:37 UTC, twaugh requested changes

2018-10-03 10:37 UTC, twaugh commented on backvendor/display_test.go
> +	const expected string = "@4309345093405934509 =v0.0.1 ~v0.0.0.20181785"
You can remove `string` from this declaration (and the other similar ones) as the type is inferred from the value.

2018-10-03 10:37 UTC, twaugh commented on backvendor/display_test.go
> +	var tmpl, err = Display("")
This would normally be written `tmpl, err := Display("")`

2018-10-03 10:37 UTC, twaugh commented on backvendor/display_test.go
> +	tmpl.Execute(&builder, ref)
We should probably check for errors from this call, and the other similar ones.

2018-10-03 10:37 UTC, twaugh commented on backvendor/display_test.go
> +	ref := &Reference{Rev: "v0.0.0.20181785", Ver: "4309345093405934509"}
The Rev and Ver fields look like their values are swapped. Rev is a revision (commit ID), Ver is a semantic version or pseudo-version.

2018-10-03 10:37 UTC, twaugh commented on main.go
> +		log.Warningf("Error parsing supplied template, using default. %s ", err)
I'd rather just abort at this point (`log.Fatalf`) rather than falling back to the default template.

2018-10-04 11:49 UTC, twaugh commented
The merge history of this branch is quite messy:
```
| *   a61eba7 -- Merge branch 'output-template' of github.com:jasinner/backvendor into output-template (35 hours ago)
| |\  
| | * 8628b57 -- added template for output (2 days ago)
| |/  
|/|   
| * eb48431 -- added template for output (35 hours ago)
|/  
* 1dd351b (tag: v0.0.4)
```

Could you please re-base it onto master so there is just a single commit with the changes? (I couldn't see how to do this myself without creating a new commit from "git diff master output-template"...)

In general it is quite usual with GitHub to have a feature branch whose existing commits you amend, and force-push the changes. Instead of merging the master branch into the feature branch, re-base the feature branch on top of the master branch. GitHub knows how to track all of that -- it just follows the branch name wherever it goes.

2018-10-05 02:15 UTC, closed without merging